on:
  pull_request:
    branches:
    - main

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  second:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ "a" == "a" }}
    steps:
      - name: echo
        run: echo "hello"

  secondTwo:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ success() && ("a" == "a") }}
    steps:
      - name: echo
        run: echo "hello"
