on:
  pull_request:
    branches:
    - main

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1

  secondTrue:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ true }}
    steps:
      - name: echo
        run: echo "hello"

  secondSuccessAndTrue:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ success() && true }}
    steps:
      - name: echo
        run: echo "hello"

  secondFailureAndTrue:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ failure() && true }}
    steps:
      - name: echo
        run: echo "hello"
        
  secondAlwaysAndTrue:
    runs-on: ubuntu-latest
    needs: first
    if: ${{ always() && true }}
    steps:
      - name: echo
        run: echo "hello"
